### ISSUE TITLE
Wrong response type in implicit code flow token builder

### ISSUE THREAD

**Issue by ohmree** [Emilgardis/twitch_oauth2#77]
Line 503 of the following file has `"response_type": "code"` whereas the implicit code flow requires `"response_type": "token"`.
This causes `ImplicitUserTokenBuilder::generate_url` to create an authorization code flow url instead.
https://github.com/Emilgardis/twitch_oauth2/blob/4956b24703f7b317533d4c110f5e959311da3962/src/tokens/user_token.rs#L497-L521

**Comment by Emilgardis** [comment]
Thank you!
